# Generated by Django 5.2.5 on 2025-08-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobs",
            name="Location",
            field=models.CharField(max_length=100),
        ),
    ]
