# Generated by Django 5.2.5 on 2025-08-29 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0008_rename_location_jobs_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobs",
            name="posted_by",
        ),
    ]
