# Generated by Django 5.2.5 on 2025-08-29 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0011_alter_application_job_id_alter_application_user_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="application",
            old_name="job_id",
            new_name="job",
        ),
        migrations.RenameField(
            model_name="application",
            old_name="user_id",
            new_name="user",
        ),
    ]
