# Generated by Django 5.2.5 on 2025-09-03 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0013_alter_application_job_alter_application_user_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="application",
            name="status",
            field=models.CharField(default="Not Applied"),
        ),
    ]
