# Generated by Django 5.2.5 on 2025-09-04 07:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0016_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="messages",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
