# Generated by Django 5.2.5 on 2025-08-29 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_alter_jobs_posted_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="jobs",
            old_name="Location",
            new_name="location",
        ),
    ]
