# Generated by Django 5.2.5 on 2025-09-03 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0014_application_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="application",
            name="status",
        ),
    ]
